# Generated by Django 4.2.1 on 2023-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='family_photos/')),
                ('parent', models.CharField(max_length=100)),
                ('dead', models.BooleanField(default=False)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='family_tree.familymember')),
                ('siblings', models.ManyToManyField(blank=True, to='family_tree.familymember')),
            ],
        ),
    ]
