# Generated by Django 4.2.1 on 2023-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='children',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='siblings',
        ),
        migrations.AddField(
            model_name='familymember',
            name='children',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='siblings',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
