# Generated by Django 4.2.2 on 2023-06-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_remove_familymember_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='dob',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100),
        ),
    ]
