# Generated by Django 4.2.2 on 2023-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_familymember_dob_familymember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='siblings',
        ),
        migrations.AddField(
            model_name='familymember',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='family_tree.familymember'),
        ),
    ]
