# Generated by Django 4.2.1 on 2023-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_alter_familymember_dob_alter_familymember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
