# Generated by Django 4.2.2 on 2023-06-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
